from __future__ import annotations

from modal_sana.models.base import ModelSpec

SANA_MODELS: tuple[ModelSpec, ...] = (
    ModelSpec(
        id="sana-sprint-1.6b",
        name="SANA-Sprint-1.6B",
        family="sana-sprint",
        hf_id="Efficient-Large-Model/Sana_Sprint_1.6B_1024px_diffusers",
        pipeline="sana-sprint",
        default_steps=2,
        default_guidance=4.5,
        recommended_dtype="bfloat16",
        description="Default. Official SANA-Sprint 1024px, 1-4 steps.",
        min_vram_gb=16,
        recommended_gpu="L40S",
        native_width=1024,
        native_height=1024,
    ),
    ModelSpec(
        id="sana-sprint-0.6b",
        name="SANA-Sprint-0.6B",
        family="sana-sprint",
        hf_id="Efficient-Large-Model/Sana_Sprint_0.6B_1024px_diffusers",
        pipeline="sana-sprint",
        default_steps=2,
        default_guidance=4.5,
        recommended_dtype="bfloat16",
        description="Smaller Sprint 1024px. Fastest and cheapest.",
        min_vram_gb=16,
        recommended_gpu="L40S",
        native_width=1024,
        native_height=1024,
    ),
    ModelSpec(
        id="sana-1.6b",
        name="SANA-1.6B",
        family="sana",
        hf_id="Efficient-Large-Model/Sana_1600M_1024px_diffusers",
        pipeline="sana",
        default_steps=20,
        default_guidance=4.5,
        recommended_dtype="bfloat16",
        description="SANA 1.0 1024px. 20 steps. Not 4K.",
        min_vram_gb=24,
        recommended_gpu="L40S",
        native_width=1024,
        native_height=1024,
    ),
    ModelSpec(
        id="sana-1.5-1.6b",
        name="SANA-1.5-1.6B",
        family="sana-1.5",
        hf_id="Efficient-Large-Model/SANA1.5_1.6B_1024px_diffusers",
        pipeline="sana",
        default_steps=20,
        default_guidance=4.5,
        recommended_dtype="bfloat16",
        description="SANA 1.5 quality line. Official 1024px only — not 4K.",
        min_vram_gb=24,
        recommended_gpu="L40S",
        native_width=1024,
        native_height=1024,
    ),
    ModelSpec(
        id="sana-1.5-4.8b",
        name="SANA-1.5-4.8B",
        family="sana-1.5",
        hf_id="Efficient-Large-Model/SANA1.5_4.8B_1024px_diffusers",
        pipeline="sana",
        default_steps=20,
        default_guidance=4.5,
        recommended_dtype="bfloat16",
        description="Largest SANA 1.5 1024px. Not 4K. Needs L40S / H100.",
        min_vram_gb=40,
        recommended_gpu="L40S",
        native_width=1024,
        native_height=1024,
        recommended_batch=2,
    ),
    ModelSpec(
        id="sana-1.6b-2k",
        name="SANA-1.6B-2K",
        family="sana",
        hf_id="Efficient-Large-Model/Sana_1600M_2Kpx_BF16_diffusers",
        pipeline="sana",
        default_steps=20,
        default_guidance=5.0,
        recommended_dtype="bfloat16",
        description="Official SANA 1.0 2K weights. Native 2048×2048.",
        min_vram_gb=40,
        recommended_gpu="L40S",
        native_width=2048,
        native_height=2048,
        recommended_batch=1,
        vae_tiling=True,
        prefetch_by_default=False,
    ),
    ModelSpec(
        id="sana-1.6b-4k",
        name="SANA-1.6B-4K",
        family="sana",
        hf_id="Efficient-Large-Model/Sana_1600M_4Kpx_BF16_diffusers",
        pipeline="sana",
        default_steps=20,
        default_guidance=5.0,
        recommended_dtype="bfloat16",
        description="Official SANA 1.0 4K weights. Native 4096×4096. VAE tiling on. Expensive.",
        min_vram_gb=48,
        recommended_gpu="H100",
        native_width=4096,
        native_height=4096,
        recommended_batch=1,
        vae_tiling=True,
        prefetch_by_default=False,
    ),
)
